In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
b=np.array([[1,2,3,4],[4,5,6,7],[7,5,6,8]])
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 5, 6, 8]])

In [7]:
c=np.array([[[1,2,3,4],[4,5,6,7],[7,5,6,8]],
            [[1,2,3,4],[4,5,6,7],[7,5,6,8]],
            [[1,2,3,4],[4,5,6,7],[7,5,6,8]],
            [[1,2,3,4],[4,5,6,7],[7,5,6,8]]])
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 5, 6, 8]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 5, 6, 8]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 5, 6, 8]],

       [[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 5, 6, 8]]])

In [10]:
d=np.arange(1,16)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
d=np.arange(1,19).reshape(3,6)
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [20]:
a=np.array([np.arange(1,9),np.arange(9,16),np.arange(16,24),np.arange(24,32)])
a

C:\Users\madan\AppData\Local\Temp\ipykernel_4676\1626888316.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a=np.array([np.arange(1,9),np.arange(9,16),np.arange(16,24),np.arange(24,32)])


array([array([1, 2, 3, 4, 5, 6, 7, 8]),
       array([ 9, 10, 11, 12, 13, 14, 15]),
       array([16, 17, 18, 19, 20, 21, 22, 23]),
       array([24, 25, 26, 27, 28, 29, 30, 31])], dtype=object)

In [25]:
a=np.arange(2,20,4)
a

array([ 2,  6, 10, 14, 18])

In [26]:
a=np.arange(20,2,-4)
a

array([20, 16, 12,  8,  4])

In [29]:
a=np.arange(15,-2,-5)
a

array([15, 10,  5,  0])

In [30]:
a=np.arange(15,-15,-5)
a

array([ 15,  10,   5,   0,  -5, -10])

In [31]:
a=np.linspace(2,30,10)
a

array([ 2.        ,  5.11111111,  8.22222222, 11.33333333, 14.44444444,
       17.55555556, 20.66666667, 23.77777778, 26.88888889, 30.        ])

In [35]:
b=np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [37]:
b=np.ones(6)
b

array([1., 1., 1., 1., 1., 1.])

In [40]:
b=np.empty(2)
b

array([4.13214046e-293, 4.62165605e-202])

In [42]:
x = np.ones(25, dtype=np.int64)
x

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1], dtype=int64)

In [43]:
a=np.array([[8,7,5],[10,3,9],[2,8,4]])
a

array([[ 8,  7,  5],
       [10,  3,  9],
       [ 2,  8,  4]])

In [44]:
a[1:,]#accesing the values in array

array([[10,  3,  9],
       [ 2,  8,  4]])

In [46]:
a[:,2]

array([5, 9, 4])

In [47]:
a[2]

array([2, 8, 4])

In [50]:
a[:,1]

array([7, 3, 8])

In [51]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
a[1:3,1:3]*5

array([[35, 40],
       [60, 65]])

In [58]:
a=np.array([1,2,3,4,5])#concatenate
b=np.array([6,7,8,9,10])
c=np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
a=np.array([8,9,6,7,5])
np.sort(a)

array([5, 6, 7, 8, 9])

In [68]:
a=np.zeros((3,3,3),dtype=np.int)
a

C:\Users\madan\AppData\Local\Temp\ipykernel_4676\4006670915.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.zeros((3,3,3),dtype=np.int)


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [70]:
a=np.zeros((3,3,3),dtype=np.int)
print(a)
b=np.ones((3,3,3),dtype=np.int)
print(b)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


C:\Users\madan\AppData\Local\Temp\ipykernel_4676\1029409879.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.zeros((3,3,3),dtype=np.int)
C:\Users\madan\AppData\Local\Temp\ipykernel_4676\1029409879.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link

In [73]:
my_array = np.array([1,2,3,4,5,6,7,8,9])
print(np.reshape(my_array,(3,3)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
a=np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [84]:
a=np.array([[1,2],[3,4]])
b=np.transpose(a)
print(b)
c=a.flatten()
print(c)

[[1 3]
 [2 4]]
[1 2 3 4]


In [78]:
c=np.flatten(b)

AttributeError: module 'numpy' has no attribute 'flatten'

In [92]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[9,6,7]])
print(a)
print(b)

c=np.concatenate([a,b],axis=0)
print(c)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [9 6 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 6 7]]


In [115]:
p=np.array([4,3,2])
a=np.array([[1,2],[1,2],[1,2],[1,2]])
b=np.array([[3,4],[3,4],[3,4]])
d=np.concatenate((a,b),dtype=int)
print(d)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [116]:
a=np.array([[[1,2,3,4,5],[6,7,8,9,10]],
           [[1,2,3,4,5],[6,7,8,9,10]],
           [[1,2,3,4,5],[6,7,8,9,10]]])
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [117]:
a.shape

(3, 2, 5)

In [118]:
a.size

30

In [119]:
a.ndim

3

In [123]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [127]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
a=np.array([[1, 2, 3],
       [4, 5, 6]])
a.shape

(2, 3)

In [131]:
b=np.array([1,2,3,4,5,6])
b.shape

(6,)

In [132]:
b=a[np.newaxis,:]
b

array([[[1, 2, 3],
        [4, 5, 6]]])

In [133]:
b.shape

(1, 2, 3)

In [134]:
b.reshape(3,2,3)
b

ValueError: cannot reshape array of size 6 into shape (3,2,3)

In [147]:
b=np.arange(1,26).reshape(5,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [148]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b=(a>=5)
print(a[b])

[ 5  6  7  8  9 10 11 12]


In [149]:
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


C:\Users\madan\AppData\Local\Temp\ipykernel_4676\2836684996.py:1: RuntimeWarning: divide by zero encountered in remainder
  print(a%b)


In [150]:
c=(a>2)
print(a[c])

[ 3  4  5  6  7  8  9 10 11 12]


In [152]:
d = a[(a > 2) & (a < 11)]
print(d)

[ 3  4  5  6  7  8  9 10]


In [155]:
e = a[(a ==2) | (a < 11)]
print(e)

[ 1  2  3  4  5  6  7  8  9 10]


In [156]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [159]:
np.vstack((a1,a2))#arranging the two arrays one beloe the one below vertically

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [160]:
np.hstack((a1,a2))#arranging the two arrays one beloe the one below horizontally

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [161]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [166]:
d=np.hsplit(x,4)
d

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [170]:
d=np.vsplit(x,3)
d

ValueError: array split does not result in an equal division

In [171]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [175]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=1)

array([2, 4])

In [176]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)

array([3, 3])

In [177]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
print(a.sum())
print(a.sum(axis=0))#rows
print(a.sum(axis=1))#rows

4.8595784
[1.12378257 1.04875507 1.01034462 1.67669614]
[1.51832856 1.55434556 1.78690428]


In [179]:
print(a.min())
print(a.min(axis=0))
print(a.min(axis=1))
print(a.max())
print(a.max(axis=1))
print(a.max(axis=1))

0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]
[0.17296777 0.05093587 0.12697628]
0.82485143
[0.5510652  0.55645993 0.82485143]
[0.5510652  0.55645993 0.82485143]


In [185]:
a=([[1,2],[3,4]],
    [[5,4],[3,9]])
b=a=([[1,2],[3,4]],
    [[5,4],[3,9]])
a-b

TypeError: unsupported operand type(s) for -: 'tuple' and 'tuple'

In [1]:
#practice
import numpy as np

In [2]:
array=np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [4]:
np.ndim(array)

1

In [5]:
np.shape(array)

(4,)

In [7]:
np.size(array)

4

In [8]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.ndim(a)

2

In [10]:
np.shape(a)

(3, 3)

In [11]:
np.size(a)

9

In [24]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,78,9]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, 78,  9]]])

In [16]:
np.ndim(a)

3

In [17]:
np.shape(a)

(3, 3, 3)

In [18]:
np.size(a)

27

In [27]:
a[2,2,1]

78

In [30]:
a[0:1]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
a=np.arange(1,1000,50)
a

array([  1,  51, 101, 151, 201, 251, 301, 351, 401, 451, 501, 551, 601,
       651, 701, 751, 801, 851, 901, 951])

In [34]:
np.size(a)

20

In [35]:
a=np.arange(1,1000,50).reshape(4,5)
a

array([[  1,  51, 101, 151, 201],
       [251, 301, 351, 401, 451],
       [501, 551, 601, 651, 701],
       [751, 801, 851, 901, 951]])

In [41]:
b=np.random.randint(1, 100,100, dtype=int)
b

array([ 4, 21, 79, 13, 41, 54, 53, 15, 40, 15, 98,  1, 58, 18, 58, 81, 41,
       21, 80, 51, 79, 39, 24, 71, 90, 71, 89, 33,  2, 84, 50, 33, 45, 27,
       29, 66, 74, 28, 20, 13, 83, 21, 29, 50, 84,  8, 57, 14, 78,  4, 68,
       53, 27, 19, 66, 96, 59, 30,  3, 11, 56, 12, 32, 24, 75, 24, 83, 63,
       52, 82, 11, 22, 37, 27, 26,  1, 19,  5, 41, 44, 17, 10, 26, 50, 90,
       70, 18, 18, 43, 55, 85, 56, 12,  9, 34, 73, 68, 62, 18, 45])

In [46]:
b=np.random.power(5)
b

0.8764908823754984

In [77]:
c=np.random.randn(1,7,10)
c

array([[[-1.12142621, -0.17933634,  1.15768097, -2.49003754,
         -1.10807014, -0.69017881, -0.17523788, -0.59905497,
          0.69116661,  1.20525901],
        [ 1.99009949, -1.53755219, -1.75213564,  0.47437938,
         -0.50952377, -1.40609039, -1.10407302, -1.00806602,
         -1.10512486,  1.19630453],
        [ 1.52326221,  0.38578871, -1.67489025, -1.35751945,
          1.10343496, -1.59725888, -0.06024608,  0.1524898 ,
          0.1531395 , -0.39508427],
        [-1.44722164,  0.33280958, -1.46942482,  0.32178271,
         -1.66185513,  0.35144395,  1.78557119,  0.37587227,
          1.36896809,  1.42889983],
        [-0.27810553,  1.12965573, -1.15498842, -0.38451685,
         -1.13591561,  0.63854137, -1.71001453, -0.40384931,
          0.04758087, -2.79628136],
        [ 1.55969765, -1.35232363,  1.23650761,  2.12960283,
         -1.55085526,  0.35422812,  1.8602276 ,  1.09160587,
          0.88167481, -0.28808125],
        [-0.64334615,  1.04621709,  0.12553808,  0.6

In [82]:
b=np.random.poisson(0.5)
b

2

In [115]:
b=np.random.logseries(0.5,10000)
b

array([2, 1, 1, ..., 1, 1, 1])

In [118]:
b=np.random.random_integers(1,5,500)
b

C:\Users\madan\AppData\Local\Temp\ipykernel_13516\1734289333.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  b=np.random.random_integers(1,5,500)


array([3, 4, 5, 1, 2, 4, 5, 3, 4, 5, 5, 5, 5, 2, 1, 5, 2, 1, 5, 2, 3, 3,
       1, 3, 3, 4, 3, 5, 1, 1, 1, 1, 2, 2, 2, 5, 4, 1, 1, 5, 1, 1, 4, 1,
       4, 5, 4, 3, 4, 4, 1, 5, 3, 4, 1, 1, 4, 1, 3, 4, 3, 3, 3, 3, 3, 5,
       5, 2, 4, 1, 2, 3, 1, 4, 3, 2, 1, 1, 5, 2, 1, 3, 4, 1, 1, 3, 1, 1,
       1, 2, 2, 1, 3, 5, 2, 3, 3, 5, 5, 2, 4, 4, 5, 2, 3, 5, 3, 5, 2, 2,
       5, 1, 1, 1, 5, 4, 4, 5, 4, 3, 2, 4, 5, 4, 5, 3, 2, 3, 4, 3, 4, 2,
       3, 2, 1, 3, 3, 5, 1, 4, 2, 4, 1, 4, 5, 2, 3, 5, 2, 3, 2, 4, 4, 2,
       3, 2, 2, 2, 2, 5, 1, 4, 4, 5, 3, 2, 3, 3, 2, 1, 3, 2, 4, 5, 3, 1,
       1, 1, 5, 3, 4, 5, 2, 1, 5, 2, 1, 5, 1, 3, 4, 3, 2, 2, 4, 5, 3, 2,
       4, 5, 5, 1, 4, 4, 2, 5, 4, 5, 2, 5, 2, 4, 5, 5, 2, 1, 3, 3, 4, 2,
       1, 2, 1, 4, 5, 1, 3, 2, 1, 2, 1, 2, 4, 5, 4, 3, 5, 2, 5, 4, 5, 5,
       3, 2, 4, 3, 5, 2, 4, 3, 1, 2, 3, 2, 2, 2, 4, 2, 3, 4, 1, 1, 5, 2,
       2, 3, 3, 2, 5, 4, 4, 3, 2, 1, 5, 2, 4, 2, 4, 4, 4, 4, 4, 4, 1, 3,
       3, 2, 2, 5, 3, 2, 2, 4, 1, 1, 2, 1, 3, 1, 5,

In [121]:
b=np.random.random_sample(100)
b

array([0.81648311, 0.24902513, 0.2693361 , 0.26452227, 0.34161653,
       0.96947206, 0.01672105, 0.6418938 , 0.71624207, 0.42855756,
       0.72104514, 0.32782013, 0.77826605, 0.01422932, 0.47089102,
       0.64744146, 0.56151877, 0.72326287, 0.05712709, 0.50759488,
       0.6725121 , 0.73176504, 0.75194181, 0.50221303, 0.90680204,
       0.34818333, 0.27974722, 0.18254616, 0.1812517 , 0.35740739,
       0.73970135, 0.83190456, 0.40580677, 0.77137245, 0.75083605,
       0.89373358, 0.23703327, 0.7121267 , 0.78044302, 0.81176448,
       0.97492419, 0.27279793, 0.33615174, 0.00455931, 0.08340069,
       0.72133224, 0.64884861, 0.6728174 , 0.03121181, 0.42434213,
       0.83904462, 0.57317199, 0.94981015, 0.36806823, 0.8226138 ,
       0.3935734 , 0.89692354, 0.67051566, 0.02189885, 0.4622183 ,
       0.59021758, 0.08607525, 0.79284122, 0.44091592, 0.21584868,
       0.61692713, 0.80525832, 0.94082173, 0.77911623, 0.87926296,
       0.85325063, 0.58470031, 0.43613017, 0.06414362, 0.25697

In [125]:
a=5
b=np.power(a,5)
b

3125

In [131]:
a=np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [132]:
a=np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
a=np.eye(5,5)
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
a[0,2]=3
a

array([[1., 0., 3., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [138]:
a[-1,-4]=10
a

array([[ 1.,  0.,  3.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0., 10.,  0.,  0.,  1.]])

In [140]:
a=np.linspace(1,10,30)
a

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [153]:
a=np.array([10,25,2,7,7,8,8,8,9,5,5,3])
a

array([10, 25,  2,  7,  7,  8,  8,  8,  9,  5,  5,  3])

In [144]:
np.unique(a)

array([2, 3, 5, 7, 8, 9])

In [145]:
np.median(a)

7.0

In [146]:
np.mean(a)

6.2

In [151]:
np.mod([1,2,3])

TypeError: remainder() takes from 2 to 3 positional arguments but 1 were given

In [154]:
np.msort(a)

array([ 2,  3,  5,  5,  7,  7,  8,  8,  8,  9, 10, 25])

In [155]:
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,8,9]],
            [[1,2,3],[4,5,6],[7,78,9]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7, 78,  9]]])

In [160]:
a.argmax(axis=1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [3]:
import numpy as np
a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
c=np.asarray(a).reshape(3,3,3, order="F")
a

ValueError: cannot reshape array of size 12 into shape (3,3,3)

In [6]:
np.ndim(a)

1

In [18]:
array_2d= np.array([[1.1,2.2,3.3],[4.4,5.5,6.6],[7.7,8.8,9.9]])
array_2d.astype(int)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a)
b=a.reshape(3,4)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
np.reshape

In [24]:
import pandas as pd
import numpy as np

In [23]:

num=[58,52,43,29,69,7,86,14,65,69,93,65,33,61,50,6,24]
frame=pd.dataframe()




AttributeError: module 'numpy' has no attribute 'data'

In [29]:
a=[ 12,13,17,21,24, 24, 26,27, 27, 30, 32, 35, 37, 38, 41, 43, 44, 46,53,60]
b=[34, 14, 31, 59, 11, 50, 27, 33, 53, 34, 13, 13, 42, 29, 33, 42, 34, 33, 44, 21]
avg_1=np.mean(a)
avg_2=np.mean(b)
print(avg_1,avg_2)
df_1=pd.DataFrame(a,,columns=[['a']])
df_2=pd.DataFrame(a,,columns=[['a']])

print(df)

32.5 32.5


ValueError: Shape of passed values is (20, 1), indices imply (20, 2)

In [1]:
import numpy as np
import pandas as pd


In [17]:
a={'profit':[1000,2000,3000,4000,5000]}
df=pd.DataFrame(data=a,index=[1,2,3,4,5])
df['10%prof']=df.profit*10
df['units']=[10,20,30,40,50]
df['percentile']=df.profit/100
print(df)

   profit  10%prof  units  percentile
1    1000    10000     10        10.0
2    2000    20000     20        20.0
3    3000    30000     30        30.0
4    4000    40000     40        40.0
5    5000    50000     50        50.0


In [27]:
a=np.ndarray([1,2,3,4,5])
print(a)
df1=pd.Series[data=a]
print(df1)

SyntaxError: invalid syntax (3850764034.py, line 3)

In [34]:
a=np.array(['a','b','c','d'])
df1=pd.Series(a)
print(df1)

0    a
1    b
2    c
3    d
dtype: object


In [ ]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print s

In [37]:
d={'a':1,'b':2,'c':3}
df2=pd.Series(d)
print(df2)

a    1
b    2
c    3
dtype: int64


In [38]:
s = pd.Series([1,2,3,4,5],index = ['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
a={'profit':[1000,2000,3000,4000,5000]}
df=pd.DataFrame(data=a,index=[1,2,3,4,5])
df['10%prof']=df.profit*10
df['units']=[10,20,30,40,50]
df['percentile']=df.profit/100
print(df)

In [42]:
df.groupby(df.profit)([df.'10%prof']).mean()

SyntaxError: invalid syntax (542489464.py, line 1)

In [44]:
#dataframe
data = {'Name':['Tom', 'Jack', 'Steve', 'Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42


In [54]:
n_a=[['madan',26],['mom',50],['dad',60],[1,2,3]]
df=pd.DataFrame(n_a,columns=['name','age','nan'],index=['rank3','rank2','rank1','rank4'])
df

name  age  nan
rank3  madan   26  NaN
rank2    mom   50  NaN
rank1    dad   60  NaN
rank4      1    2  3.0

In [56]:
p={{'one':[np.linspace(1,5,20)]},{'two':[np.linspace(1,10,20)]},{'three':[np.linspace(1,15,20)]},{'one':[np.linspace(1,5,20)]}}

TypeError: unhashable type: 'dict'

In [57]:
d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


In [62]:
a=[1,54,87,98,87,65,32,54,57,95,52]
b=np.max(a)
print(b)
c=np.min(a)
d=np.mean(a)
e=np.median(a)
#f=np.mod(a)
g=np.var(a)
k=np.std(a)
print(b,c,e,g,k)

98
98 1 57.0 774.3636363636364 27.82739003865861
